var myName = "Derek";
var myAge = 41;
var canVote = true;
var anything = "dog";
inferred = 2;
document.getElementById('ts').innerHTML = 'Hi, my name is ' + myName + '.';
document.write('myName is a ' + typeof (myName) + '<br>');
document.write('myAge is a ' + typeof (myAge) + '<br>');
document.write('canVote is a ' + typeof (canVote) + '<br>');
document.write('anything is a ' + typeof (anything) + '<br>');
document.write('inferred is a ' + typeof (inferred) + '<br>');
